### PR TITLE
mkimage.sh.in: don't keep going if sfdisk fails.

### PR DESCRIPTION
**Pull request by CMB**
Also added a call to sfdisk -V to verify the consistency of the
partition table.  I thought about listing the partitions and
trying to check the list against expectations, but that's overkill.

### CODE REVIEW

**Comment by chneukirchen** [comment]
Wouldn't it be a bug in sfdisk if it creates a disklabel it can't verify?

**Comment by CMB** [comment]
Yes, I think so.  I added the verification step, because I've seen comments
on the net indicating that sfdisk exit codes might be unreliable.
It's just an extra sanity check that can probably be removed.
Let me know, and I'll update the PR.

**Comment by the-maldridge** [comment]
Having now overseen a few thousand void installs, I have not ever seen an sfdisk error that didn't correctly die.  As such I'm going to go ahead and close out this issue.

**Comment by CMB** [comment]
See pull request 89 and issue 81.  This was a follow-on patch to 89.
Basically, several of us were getting unbootable ARM images
because mkimage.sh marched forward after an sfdisk failure.

**Pull request closed without merging**
