### PR TITLE
adding virtualbox guest support

### PR DESCRIPTION
**Pull request by antonio-malcolm**
This adds virtualbox-ose-guest to the base packages, and xrandr to the x packages, to support usage of the x86 UI environment images as virtualbox live disks.

This resolves issue #109

### CODE REVIEW

**Comment by Vaelatern** [comment]
This is a very large package to build. Just on that I feel it might be inappropiate to add this package.

**Comment by antonio-malcolm** [comment]
In comparison to what already is built into the environments? 
Well, your environment-equipped live disks won't work in Virtualbox without it.
If someone wants to test Void in a VM, and/or use a live image to easily install as a VM, they will not likely be able to do so.
However, maybe no one uses or cares about this, which is fair enough.

**Comment by the-maldridge** [comment]
This is not an acceptable change as it breaks one path through the installer.  If you boot from media with this patch and then install using the '<local>' source, you will wind up with the virtualbox guest extensions installed on the now physical system.  There are long term plans to provide virtualization images of Void, but those are on hold pending more pressing concerns with the project.

**Comment by antonio-malcolm** [comment]
Ok, so it's not possible to omit the module?
Ah, nevermind. Forget it.

**Comment by the-maldridge** [comment]
You could remove the module, but you'd still need a post-copy step to chroot into the installed environment and remove the package.

The end goal of this PR could be solved by shipping the *.xbps files for the guest extensions and then installing them as a startup task if the machine detects that its running on a virtualized CPU.  I personally think this is a huge amount of effort for not much gain, but it does solve the case where you somehow have an entire hypervisor environment, but don't have network access to the repository.

**Pull request closed without merging**
