### PR TITLE
installer.sh.in: add ISO-639 and ISO-3166 tables

### PR DESCRIPTION
**Pull request by pullmoll**
The locale selection now has user friendly names for language
and country.

### CODE REVIEW

**Comment by Gottox** [comment]
Can we please remove bashisms from the installer instead of adding them?

**Comment by pullmoll** [comment]
FYI @gottox Doing the same without bashisms using 2 tmpfiles for languages and countries, and then `grep`, `sed`, `cut` to build the list takes more than 5 seconds here.

Do you intend to use the installer with `sh` at some point?

**Comment by Gottox** [comment]
I find it tempting to ship the install cd with a busybox base.

**Comment by pullmoll** [comment]
Well, without bash this patch is not usable. So be it.

**Pull request closed without merging**
