### PR TITLE
Umask

### PR DESCRIPTION
**Pull request by emdete**
fixes bug when mklive script is not run with umask 022 (sorry, depends on error_out bugfix)

### CODE REVIEW

**Comment by Gottox** [comment]
@xtraeme what do you think about the umask fix?

The error_out fix looks okay to me.

**Comment by the-maldridge** [comment]
@emdete please rebase onto master at your earliest convenience.

@Gottox I'm satisfied with this patch, do you have any lingering concerns?

**Comment by Gottox** [comment]
Please resolve the conflicts

**Comment by the-maldridge** [comment]
resolved in fe57bb4

**Pull request closed without merging**
