### PR TITLE
mklive.sh: simplify finding KERNELVERSION by searching after "$ROOTFS…

### PR DESCRIPTION
**Pull request by mobinmob**
…" is populated.

### CODE REVIEW

**Comment by ebfe** [comment]
What is wrong with the current approach? Using xbps-query seems reasonable and more reliable than matching/seding filenames in /boot.

**Comment by mobinmob** [comment]
The current approach is using xbps-query, xbps-uhelper and 2 variables to try and find the kernel version. That seems a bit overkill to me and is nessesary only if you need to find the kernel version *before* the installation of the kernel package in the $ROOTFS. After the installation, there is exactly one file named vmlinux-$KERNELVERSION in $ROOTFS/boot and it much simpler to get the kernel version from that. There is absolutely nothing wrong with the current approach, I just find it needlesly complicated. :)

**Comment by Duncaen** [comment]
What happens if someone adds multiple kernel packages?
What happens if the kernel is no gz compressed?

**Comment by ebfe** [comment]
> If you want to account for multiple kernel packages installed  (certainly possible, but not exactly something I 'll expect in a live cd), then the relevant live becomes:
> `KERNELVERSION=$(find "$ROOTFS"/boot/ -name "vmlinuz-*" -print|head -1|sed 's|.*\-\(.*\)|\1|'`
> If you want to account for changes in the kernel image name (are there any kernel images with different names/compression in the repos; ), you can use the config file or the System.map file to extract the kernel version.

Or you could simplify the whole thing by asking the package manager for
the current version of the linux meta package.

**Comment by mobinmob** [comment]
Got it! My simple approach gets really  complicated. Thank you. 🙂

**Pull request closed without merging**
