### PR TITLE
display-manager-autologin.sh: add fluxbox/openbox support

### PR DESCRIPTION
**Pull request by cr6git**
Proposal: it would be great to have a `void-live-fluxbox.iso` in [/live/current/](https://repo.voidlinux.eu/live/current/)

### CODE REVIEW

**Comment by Vaelatern** [comment]
This would not be all the changes needed.

**Comment by the-maldridge** [comment]
Is the goal here just to support this for custom ISOs or to make this something that would be in a full release?  If this is just support, that changes the requirements dramatically.

**Comment by cr6git** [comment]
Of course, an official fluxbox release would require additional work, and I would be very happy to work on this project. 

With this simple modification in `display-manager-autologin.sh` , at least, we can already create a fluxbox live ISO with autologin. 
Give it a try with just a limited number of packages, for example: 
````
./mklive.sh -p "cpupower xorg fluxbox lxterminal lxdm gparted"
````
good night friends ;)

**Comment by cr6git** [comment]
Plus we have [fbmenugen](https://github.com/voidlinux/void-packages/pull/9496). 😉

**Comment by cr6git** [comment]
As `openbox` is very popular nowadays, we could also add it to the list...
````
elif [ -x ${NEWROOT}/usr/bin/openbox-session ]; then
    sed -e "s,.*session.*=.*,session=/usr/bin/openbox-session," -i ${NEWROOT}/etc/lxdm/lxdm.conf
````

**Pull request closed without merging**
