### PR TITLE
mklive.sh.in: update repos

### PR DESCRIPTION
**Pull request by cr6git**

### CODE REVIEW

**Comment by the-maldridge** [comment]
Not good. You can't force ssl here because not all reps are serving with
ssl yet. It's down to flipping a few switches but it isn't done yet.

**Comment by cr6git** [comment]
`--repository=http://muslrepo.voidlinux.eu/current`
This repository does not work for me.

**Comment by cr6git** [comment]
From [#Official_Repositories](https://wiki.voidlinux.eu/XBPS#Official_Repositories), we can read: 
````
https://repo.voidlinux.eu/current/
https://repo.voidlinux.eu/current/musl/
````

Then why is it different with void-mklive ??

**Comment by cr6git** [comment]
OK I understand for ssl, sorry for that, I surely mistranslated your words the last time. ;)

**Comment by ebfe** [comment]
@the-maldridge Why do other repos matter in a hardcoded url?

**Comment by the-maldridge** [comment]
Once the protocol is set it won't be downgraded, even though the other repos can't serve over that protocol.  Since we are doing naive things to route traffic to other repos, this would be a problem.

**Pull request closed without merging**
