### PR TITLE
mkimage.sh.in: fix truncate size argument

### LINKED ISSUE #61: Size unit issue in mkimage.sh
Creating an image fails because `truncate -s "${IMGSIZE}M" $FILENAME >/dev/null 2>&1` adds M to the IMGSIZE variable.
For example the default IMGSIZE is 2G so it ends up being 2GM which is invalid.

### PR DESCRIPTION
**Pull request by rdamen**
fixes #61

### CODE REVIEW

**Comment by ebfe** [comment]
mklive.sh needs the same fix

**Comment by Vaelatern** [comment]
Since the documentation all has the argument in Megabytes, it would be better to fix the default size.

**Comment by ebfe** [comment]
On Thu, Feb 25, 2016 at 05:45:10PM -0800, Toyam Cox wrote:
> Since the documentation all has the argument in Megabytes, it would be better to fix the default size.

    $ ./mkimage.sh
    Usage: mkimage.sh [options] <rootfs-tarball>
    [...]
    Accepted sizes suffixes: K, M, G, T, E.
    [...]

**Comment by Vaelatern** [comment]
Ah. I was looking at mklive instead.

**Pull request merged**
