### PR TITLE
Preserve Linux capabilities when running tar, and misc fixes for mkrootfs.

### PR DESCRIPTION
**Pull request by CMB**

### CODE REVIEW

**Comment by pullmoll** [comment]
IIRC we decided to get rid of bashisms in void-installer.
There should be a way to pass `--xattrs-include='*'` without resorting to `"${tar_out[@]}"`, no?

**Comment by CMB** [comment]
I don't see an obvious way to quote --xattrs-include=* inside $tar_out.
It seems like this may even be ok unquoted, since the only way the glob
will get expanded is if someone has filenames starting with
--xattrs-include=, which is highly improbable.
If someone has a better quoting idea or wants me to remove the quotes
entirely, that's fine.

**Comment by pullmoll** [comment]
The code there does not absolutely have to use local vars for parameters.
I did it for readability, not for functionality.
You could just change it to make the tar line(s) use the required parameters.

**Comment by CMB** [comment]
Ok.  I got rid of $tar_out.  I left $tar_in alone, because it doesn't
need quoting and it is used twice.
Thanks.

**Pull request merged**
