### PR TITLE
Fix getopts using bash

### PR DESCRIPTION
**Pull request by radare**
getopts is a bashism and therefore, the implementation in dash only iterates once in the loop, so 90% of the flags are ignored without this patch

### CODE REVIEW

**Comment by Ypnose** [comment]
<code>getopts</code> is absolutely not a bashism. It's defined in POSIX.
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/getopts.html

**Comment by radare** [comment]
Uhm. Can you reproduce the issue? Ive been trying several times and the only way to get it working was to switch to bash or rewrite the options parsing loop

**Comment by Ypnose** [comment]
I did not test the script by myself, after your report (lack of time), but it could be interesting to see what <code>set -x</code> returns. And are you running that script on a Void box or somewhere else?

**Comment by radare** [comment]
im running the script using this makefile:

https://github.com/radare/radare2live

you should be able to reproduce the issue by cloning and typing make in there. the issue is that the final iso is about 190MB instead of 250MB and doesnt contains any of the selected packages (configured in the makefile)

**Comment by xtraeme** [comment]
`getops` is specified by POSIX and supported by our default shell `/bin/sh` (dash).

I don't see what's wrong, please paste output with `set -x` running `mklive.sh`.

**Comment by radare** [comment]
wtf i cant reproduce it anymore, using sh -x shows everything fine.. . so i'm not sure what was going on.

**Pull request closed without merging**
